# Generated by Django 5.1.1 on 2024-09-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrega', '0003_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ventasproducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreproducto', models.CharField(max_length=50)),
                ('Cantidaddeventas', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='Precio',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
